# 将这些配置都配置到nacos
#server:
#  port: 8082
#spring:
#  gateway:
#    routes:
#      - id: order-service
#        uri: lb://order-service
#        predicates:
#          - Path=/order/**
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#          - Path=/user/**

